import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import "./globals.css";
import Provider from "./context/Provider";
import { Toaster } from 'react-hot-toast'
import Nav from "./components/Navbar";
const poppins = Poppins({ subsets: ['latin'] ,weight:['400','700',]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
      <body className={`${poppins.className}`}>
        
      <Toaster
        toastOptions={{
          style: {
            backgroundColor:"#1F1F1F",
            color:"#FFFFFF"
          },
          duration:2500
        }}
         position='top-center'/>
         <Nav/>
        {children}
      </body>
      </Provider>
    </html>
  );
}
